<a href="https://colab.research.google.com/github/leenu10/DataScienceAnalytics/blob/main/Week15_activity_jiofibre.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
data = pd.read_csv('/content/jio fibre tcp-connection.csv')
data.shape

(93285, 42)

In [ ]:
data.head()

   duration protocol_type  ... dst_host_srv_rerror_rate    intrusion
0         0        b'udp'  ...                      0.0   b'normal.'
1         0        b'tcp'  ...                      0.0   b'normal.'
2         0       b'icmp'  ...                      0.0    b'smurf.'
3         0       b'icmp'  ...                      0.0    b'smurf.'
4         0        b'tcp'  ...                      0.0  b'neptune.'

[5 rows x 42 columns]

In [ ]:
data.duplicated().sum()

59659

In [ ]:
data = data.drop_duplicates()
data.shape

(33626, 42)

In [ ]:
data.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serrer_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  1
diff_srv_rate                  1
srv_diff_host_rate             1
dst_host_count                 1
dst_host_srv_count             1
dst_host_same_srv_rate         1
dst_host_diff_srv_rate         1
dst_host_same_src_port_rate    1
dst_host_srv_diff_host_rate    1
dst_host_serror_rate           1
dst_host_srv_serror_rate       1
dst_host_rerror_rate           1
dst_host_srv_rerror_rate       1
intrusion                      1
dtype: int64

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33626 entries, 0 to 93284
Data columns (total 42 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   duration                     33626 non-null  int64
 1   protocol_type                33626 non-null  object
 2   service                      33626 non-null  object
 3   flag                         33626 non-null  object
 4   src_bytes                    33626 non-null  int64
 5   dst_bytes                    33626 non-null  int64
 6   land                         33626 non-null  int64
 7   wrong_fragment               33626 non-null  int64
 8   urgent                       33626 non-null  int64
 9   hot                          33626 non-null  int64
 10  num_failed_logins            33626 non-null  int64
 11  logged_in                    33626 non-null  int64
 12  num_compromised              33626 non-null  int64
 13  root_shell                   33626 non-null  int64
 14  su_attempted                 33626 non-null  int64
 15  num_root                     33626 non-null  int64
 16  num_file_creations           33626 non-null  int64
 17  num_shells                   33626 non-null  int64
 18  num_access_files             33626 non-null  int64
 19  num_outbound_cmds            33626 non-null  int64
 20  is_host_login                33626 non-null  int64
 21  is_guest_login               33626 non-null  int64
 22  count                        33626 non-null  int64
 23  srv_count                    33626 non-null  int64
 24  serror_rate                  33626 non-null  float64
 25  srv_serrer_rate              33626 non-null  float64
 26  rerror_rate                  33626 non-null  float64
 27  srv_rerror_rate              33626 non-null  float64
 28  same_srv_rate                33625 non-null  float64
 29  diff_srv_rate                33625 non-null  float64
 30  srv_diff_host_rate           33625 non-null  float64
 31  dst_host_count               33625 non-null  float64
 32  dst_host_srv_count           33625 non-null  float64
 33  dst_host_same_srv_rate       33625 non-null  float64
 34  dst_host_diff_srv_rate       33625 non-null  float64
 35  dst_host_same_src_port_rate  33625 non-null  float64
 36  dst_host_srv_diff_host_rate  33625 non-null  float64
 37  dst_host_serror_rate         33625 non-null  float64
 38  dst_host_srv_serror_rate     33625 non-null  float64
 39  dst_host_rerror_rate         33625 non-null  float64
 40  dst_host_srv_rerror_rate     33625 non-null  float64
 41  intrusion                    33625 non-null  object
dtypes: float64(17), int64(21), object(4)
memory usage: 11.0+ MB

In [ ]:
for col in data.columns:
  print(data[col].value_counts())

0        31457
1          472
2          160
3          105
5           86
         ...
51           1
2034         1
10134        1
1394         1
11866        1
Name: duration, Length: 686, dtype: int64
b'tcp'     30127
b'udp'      2832
b'icmp'      667
Name: protocol_type, dtype: int64
b'private'     14830
b'http'        11742
b'smtp'         1827
b'other'        1129
b'domain_u'     1106
               ...
b'uucp'           14
b'netstat'        14
b'ctf'            12
b'X11'             4
b'urh_i'           3
Name: service, Length: 62, dtype: int64
b'SF'        17152
b'S0'        12210
b'REJ'        4007
b'RSTO'        124
b'RSTR'        106
b'SH'           12
b'S1'            6
b'S3'            3
b'S2'            2
b'RSTOS0'        2
b'OTH'           2
Name: flag, dtype: int64
0        16417
105        537
147        454
146        321
54540      227
         ...
12813        1
523          1
2570         1
47612        1
1983         1
Name: src_bytes, Length: 1722, dtype: int64
0        18568
105        702
8314       223
330        181
147        179
         ...
1998         1
8141         1
3983         1
1934         1
12202        1
Name: dst_bytes, Length: 4705, dtype: int64
0    33622
1        4
Name: land, dtype: int64
0    33398
3      185
1       43
Name: wrong_fragment, dtype: int64
0    33625
3        1
Name: urgent, dtype: int64
0     33185
2       234
1        55
28       49
6        29
4        27
5        11
14        8
3         5
30        5
19        4
22        4
20        3
24        3
7         2
17        1
12        1
Name: hot, dtype: int64
0    33601
1       23
2        2
Name: num_failed_logins, dtype: int64
0    20203
1    13423
Name: logged_in, dtype: int64
0     33388
1       228
4         4
2         3
21        1
11        1
3         1
Name: num_compromised, dtype: int64
0    33615
1       11
Name: root_shell, dtype: int64
0    33626
Name: su_attempted, dtype: int64
0     33526
1        50
9        24
6        19
2         3
5         2
12        1
3         1
Name: num_root, dtype: int64
0     33573
1        45
2         4
28        1
25        1
10        1
4         1
Name: num_file_creations, dtype: int64
0    33619
1        6
2        1
Name: num_shells, dtype: int64
0    33543
1       77
2        5
4        1
Name: num_access_files, dtype: int64
0    33626
Name: num_outbound_cmds, dtype: int64
0    33626
Name: is_host_login, dtype: int64
0    33485
1      141
Name: is_guest_login, dtype: int64
1      6338
2      1844
3      1031
4       956
5       811
       ...
484       1
363       1
438       1
458       1
465       1
Name: count, Length: 406, dtype: int64
1      5661
2      3029
3      1800
4      1572
5      1455
       ...
462       1
430       1
270       1
238       1
495       1
Name: srv_count, Length: 318, dtype: int64
0.00    21075
1.00    12100
0.99       61
0.06       24
0.08       23
        ...
0.93        1
0.42        1
0.40        1
0.85        1
0.83        1
Name: serror_rate, Length: 68, dtype: int64
0.00    21196
1.00    12208
0.03       26
0.04       23
0.06       18
0.05       17
0.02       14
0.09       11
0.33       11
0.07       11
0.20       10
0.08        9
0.10        9
0.14        8
0.25        8
0.50        8
0.12        7
0.11        5
0.17        5
0.01        3
0.76        2
0.95        1
0.91        1
0.37        1
0.40        1
0.16        1
0.88        1
0.86        1
0.90        1
0.21        1
0.75        1
0.94        1
0.22        1
0.19        1
0.93        1
0.92        1
0.67        1
0.58        1
Name: srv_serrer_rate, dtype: int64
0.00    29250
1.00     4035
0.90       20
0.50       20
0.20       18
        ...
0.58        1
0.72        1
0.60        1
0.06        1
0.35        1
Name: rerror_rate, Length: 63, dtype: int64
0.00    29179
1.00     4184
0.50       41
0.33       38
0.20       29
0.25       18
0.17       17
0.14       16
0.03       13
0.02       10
0.12        9
0.06        8
0.04        7
0.09        7
0.05        7
0.10        6
0.40        6
0.67        5
0.07        5
0.11        4
0.75        3
0.29        3
0.60        2
0.96        2
0.08        2
0.01        1
0.95        1
0.22        1
0.82        1
0.71        1
Name: srv_rerror_rate, dtype: int64
1.00    17739
0.06     1531
0.05     1471
0.04     1378
0.07     1362
        ...
0.74        1
0.79        1
0.76        1
0.87        1
0.85        1
Name: same_srv_rate, Length: 85, dtype: int64
0.00    17729
0.06     7453
0.07     3957
0.05     2606
0.08      554
        ...
0.37        1
0.28        1
0.39        1
0.58        1
0.57        1
Name: diff_srv_rate, Length: 64, dtype: int64
0.00    27344
1.00     1420
0.50      258
0.12      252
0.11      243
0.25      234
0.67      232
0.08      200
0.33      194
0.17      190
0.10      184
0.07      180
0.40      173
0.09      172
0.18      169
0.22      162
0.15      162
0.14      159
0.20      157
0.29      154
0.13      141
0.06      137
0.02      115
0.05       93
0.19       73
0.21       71
0.16       66
0.04       66
0.75       64
0.01       63
0.27       61
0.43       56
0.60       56
0.23       50
0.38       48
0.30       48
0.03       34
0.24       30
0.31       17
0.36       17
0.80       16
0.44       10
0.28        9
0.57        8
0.26        7
0.56        6
0.42        5
0.83        4
0.62        3
0.47        2
0.55        2
0.71        2
0.88        1
0.45        1
0.37        1
0.32        1
0.35        1
0.77        1
Name: srv_diff_host_rate, dtype: int64
255.0    22239
1.0        466
2.0        336
3.0        259
4.0        236
         ...
211.0       10
204.0       10
206.0        9
236.0        7
0.0          1
Name: dst_host_count, Length: 256, dtype: int64
255.0    10553
1.0       1689
2.0       1068
3.0        841
11.0       812
         ...
202.0        9
194.0        9
154.0        9
197.0        7
0.0          1
Name: dst_host_srv_count, Length: 256, dtype: int64
1.00    12412
0.04     2348
0.02     2286
0.05     2247
0.07     2136
        ...
0.61       28
0.48       28
0.37       28
0.16       25
0.23       24
Name: dst_host_same_srv_rate, Length: 101, dtype: int64
0.00    12265
0.07     6400
0.06     3940
0.05     2494
0.08     2320
        ...
0.32        2
0.35        1
0.92        1
0.96        1
0.93        1
Name: dst_host_diff_srv_rate, Length: 100, dtype: int64
0.00    20767
0.01     3924
1.00     1399
0.02     1397
0.03      793
        ...
0.68        5
0.58        5
0.60        4
0.65        4
0.66        1
Name: dst_host_same_src_port_rate, Length: 101, dtype: int64
0.00    23944
0.02     2174
0.01     1997
0.04     1263
0.03     1210
0.05      881
0.06      380
0.07      296
0.09      119
0.08      118
0.50      102
0.15       77
0.17       77
0.13       75
0.14       72
0.10       70
0.18       69
0.12       67
0.16       67
0.20       58
0.11       56
0.25       54
1.00       53
0.19       48
0.21       42
0.22       36
0.26       27
0.29       21
0.24       21
0.40       18
0.27       18
0.33       16
0.23       11
0.67       10
0.30       10
0.51        9
0.31        8
0.52        8
0.32        6
0.38        5
0.56        4
0.36        4
0.34        4
0.28        3
0.57        3
0.43        2
0.42        2
0.44        2
0.53        2
0.55        1
0.37        1
0.45        1
0.41        1
0.75        1
0.60        1
Name: dst_host_srv_diff_host_rate, dtype: int64
0.00    20173
1.00    12143
0.01      654
0.02      166
0.03       69
        ...
0.65        1
0.40        1
0.73        1
0.64        1
0.37        1
Name: dst_host_serror_rate, Length: 78, dtype: int64
0.00    20354
1.00    12198
0.01      851
0.02      110
0.03       26
0.04       14
0.05       11
0.06       10
0.11        4
0.17        3
0.75        3
0.97        3
0.14        3
0.10        2
0.62        2
0.40        2
0.09        2
0.25        2
0.07        2
0.33        2
0.16        2
0.67        1
0.69        1
0.68        1
0.30        1
0.50        1
0.91        1
0.83        1
0.94        1
0.60        1
0.96        1
0.95        1
0.56        1
0.85        1
0.98        1
0.90        1
0.08        1
0.78        1
0.87        1
0.31        1
Name: dst_host_srv_serror_rate, dtype: int64
0.00    28248
1.00     3828
0.01      298
0.02      151
0.03       85
        ...
0.23        3
0.37        2
0.61        2
0.49        2
0.46        1
Name: dst_host_rerror_rate, Length: 101, dtype: int64
0.00    28446
1.00     3728
0.01      370
0.02      133
0.04       87
        ...
0.30        1
0.26        1
0.81        1
0.46        1
0.43        1
Name: dst_host_srv_rerror_rate, Length: 96, dtype: int64
b'normal.'             17071
b'neptune.'            15089
b'back.'                 239
b'satan.'                238
b'smurf.'                225
b'teardrop.'             187
b'warezclient.'          179
b'ipsweep.'              171
b'portsweep.'            103
b'pod.'                   41
b'nmap.'                  38
b'guess_passwd.'          21
b'buffer_overflow.'        5
b'imap.'                   4
b'land.'                   4
b'loadmodule.'             3
b'rootkit.'                2
b'warezmaster.'            2
b'perl.'                   1
b'multihop.'               1
b'phf.'                    1
Name: intrusion, dtype: int64

In [ ]:
data.dropna(how='any', inplace=True)
data.shape

(33625, 42)

In [ ]:
def encode(data):
  for col in data.columns:
    data[col] = data[col].factorize()[0]
  return data

In [ ]:
encoded_data = encode(data.copy())
encoded_data.head()

   duration  protocol_type  ...  dst_host_srv_rerror_rate  intrusion
0         0              0  ...                         0          0
1         0              1  ...                         0          0
2         0              2  ...                         0          1
4         0              1  ...                         0          2
5         0              2  ...                         0          1

[5 rows x 42 columns]

In [ ]:
encoded_data['protocol_type'].unique()

array([0, 1, 2])

##splitting into target and feature variables.

In [ ]:
x = encoded_data.drop('intrusion', axis=1)
y = encoded_data['intrusion']

### splitting into train and test data.

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)

## Decision tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier
tree = DecisionTreeClassifier()

tree.fit(x_train, y_train)
y_pred = tree.predict(x_test)

from sklearn.metrics import confusion_matrix, accuracy_score

print(confusion_matrix(y_test, y_pred))
print('\n', accuracy_score(y_test, y_pred))

[[4208    0    0    3    2    0    3    1    0    0    2    0    0    0
     1    0    1]
 [   0   56    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0]
 [   0    0 3825    0    0    0    0    2    0    0    0    0    0    0
     0    0    0]
 [   3    0    0   35    0    0    0    0    0    0    0    0    0    0
     0    0    0]
 [   4    0    0    0   54    0    0    0    0    0    0    0    0    0
     0    0    0]
 [   3    0    0    0    1   59    0    0    0    0    0    0    0    0
     0    0    0]
 [   2    0    0    0    0    0   49    0    0    0    0    0    0    0
     0    0    0]
 [   1    0    0    0    1    0    0   16    0    0    0    0    0    0
     0    0    0]
 [   0    0    0    0    0    0    0    0   41    0    0    0    0    0
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    4    0    0    0    0
     0    0    0]
 [   2    0    0    0    0    0    0    0    0    0   11    0    0    0
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    1    0    0
     0    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0   11    0
     0    0    0]
 [   1    0    0    0    0    1    0    0    0    0    0    0    0    0
     0    0    0]
 [   0    0    0    0    0    0    0    1    0    0    0    0    0    0
     1    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    1    0]
 [   0    0    0    0    0    0    0    0    0    0    0    0    0    0
     0    0    0]]

 0.9958368026644463